name: Show Me the S3cr3tz
on: [workflow_dispatch]  # Recommended over 'push' for manual debugging

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Write secrets to secrets.txt
        env:
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_WORKFLOW_DATABASE_ID: ${{ secrets.NOTION_WORKFLOW_DATABASE_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        run: |
          echo "GMAIL_CLIENT_ID=$GMAIL_CLIENT_ID" >> secrets.txt
          echo "GMAIL_CLIENT_SECRET=$GMAIL_CLIENT_SECRET" >> secrets.txt
          echo "GMAIL_REFRESH_TOKEN=$GMAIL_REFRESH_TOKEN" >> secrets.txt
          echo "NOTION_API_KEY=$NOTION_API_KEY" >> secrets.txt
          echo "NOTION_DATABASE_ID=$NOTION_DATABASE_ID" >> secrets.txt
          echo "NOTION_WORKFLOW_DATABASE_ID=$NOTION_WORKFLOW_DATABASE_ID" >> secrets.txt
          echo "GEMINI_API_KEY=$GEMINI_API_KEY" >> secrets.txt
          echo "LOG_LEVEL=$LOG_LEVEL" >> secrets.txt

      - name: Run tmate (to access secrets.txt interactively)
        uses: mxschmitt/action-tmate@v2
